# Generated by Django 4.2.6 on 2023-10-07 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro_asistencia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistenciaclase',
            name='tema',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='Tema',
        ),
    ]
