# Generated by Django 4.2.6 on 2023-10-25 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registro_asistencia', '0003_alter_profesor_num_celular'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asistenciaprofesor',
            name='motivo_falta',
        ),
    ]
