# Generated by Django 4.2.6 on 2023-10-25 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro_asistencia', '0004_remove_asistenciaprofesor_motivo_falta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistenciaprofesor',
            name='hora_llegada',
            field=models.TimeField(blank=True, default='23:49:23', null=True),
        ),
    ]
